services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - web-data:/usr/share/nginx/html:ro
  ftp:
    image: fauria/vsftpd
    user: root
    environment:
      - FTP_USER=devops
      - FTP_PASS=dp1234
      - PASV_ADDRESS=localhost
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - web-data:/home/devops/www
volumes:
  web-data: