services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "8082:80"
    environment:
      - REGISTRY_TITLE=Local Registry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
volumes:
  registry-data: